# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a21ba391ecade9c2cd40157b6515d4b760e098937ab38dfb9bf109ba1ab5552a4819089e76322e9b42e5581af1ae9ad9e3f2118b0f8568d10b585a551e2d30

test:
  secret_key_base: 6ba4e5a01075f475667e8aa4d855529dd26d238add88d5c9c7fdc09f363d130dad1c76c0ded2a0293995bf58e14f98fe73d6ea6bbfcf04572dcc221a87026bd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
